import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex justify-center flex-row gap-2">
            <li>
              <Link href={"/isr"}>isr</Link>
            </li>
            <li>
              <Link href={"/ssg"}>ssg</Link>
            </li>
            <li>
              <Link href={"/csr"}>csr</Link>
            </li>
            <li>
              <Link href={"/ssr"}>ssr</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
